"""Constants and mappings for student data transformation."""

# RBD (school identifier) default value
DEFAULT_RBD = 574

# Academic year default value
DEFAULT_YEAR = 2025

# School location default value
DEFAULT_LOCAL = "Principal"

# Mapping of commune codes to names
COMUNA_CODES = {
    0: "SIN COMUNA",
    4101: "LA SERENA",
    4102: "COQUIMBO",
    4103: "ANDACOLLO",
    4104: "LA HIGUERA",
    4105: "PAIHUANO",
    4106: "VICUÑA",
    4204: "SALAMANCA",
    2101: "ANTOFAGASTA",
    3301: "VALLENAR",
    1101: "IQUIQUE",
    4302: "COMBARBALA",
    4303: "MONTE PATRIA",
    4304: "PUNITAQUI",
    4305: "RIO HURTADO",
    5602: "ALGARROBO",
}

# Mapping of grade numbers to level names
GRADE_LEVELS = {
    7: "7 Básico",
    8: "8 Básico",
    1: "1 Medio",
    2: "2 Medio",
    3: "3 Medio",
    4: "4 Medio",
}

# Patterns to clean from addresses
ADDRESS_CLEANUP_PATTERNS = [
    r"la serena|laserena|serena|laserna|la  serena|coquimbo|vicuña",
]

# Expected input CSV columns (74 columns from original system)
INPUT_COLUMNS = [
    "Rut",
    "Digito verificador",
    "Nombres",
    "Apellido Paterno",
    "Apellido Materno",
    "Sexo",
    "Fecha de Nacimiento",
    "Direccion",
    "Comuna",
    "Nombre Comuna",
    "Región",
    "Nombre Region",
    "Email Estudiante",
    "Nacionalidad",
    "Etnia",
    "Tipo de enseñanza",
    "Grado",
    "Letra",
    "Nombre Curso",
    "Repitente",
    "Alumno Nuevo",
    "Rut Apoderado",
    "Nombre Apoderado",
    "Apellido Paterno Apo.",
    "Apellido Materno Apo.",
    "Fecha de Nac. Apo.",
    "Direccion Apoderado",
    "Comuna Apoderado",
    "Nombre Comuna Apoderado",
    "Región Apoderado",
    "Nombre Region Apoderado",
    "Celular Apoderado",
    "Email Apoderado",
    "Nivel Estudio Apoderado",
    "Parentesco Apoderado",
    "Fecha de Matrícula",
    "Rut Apoderado SPL",
    "Nombre Apoderado SPL",
    "Apellido Paterno Apo. SPL",
    "Apellido Materno Apo. SPL",
    "Fecha de Nac. Apo. SPL",
    "Direccion Apoderado SPL",
    "Comuna Apoderado SPL",
    "Nombre Comuna Apoderado SPL",
    "Región Apoderado SPL",
    "Nombre Region Apoderado SPL",
    "Celular SPL",
    "Email Apoderado SPL",
    "Nivel Estudio Apoderado SPL",
    "Parentesco Apoderado SPL",
    "Rut Padre",
    "Nombre Padre",
    "Apellido Paterno Padre.",
    "Apellido Materno Padre.",
    "Fecha de Nac. Padre",
    "Direccion Padre",
    "Comuna Padre",
    "Nombre Comuna Padre",
    "Región Padre",
    "Nombre Region Padre",
    "Celular Padre",
    "Email Padre",
    "Nivel Estudio Padre",
    "Rut Madre",
    "Nombre Madre",
    "Apellido Paterno Madre",
    "Apellido Materno Madre",
    "Fecha de Nac. Madre",
    "Direccion Madre",
    "Comuna Madre",
    "Nombre Comuna Madre",
    "Región Madre",
    "Nombre Region Madre",
    "Celular Madre",
    "Email Madre",
    "Nivel Estudio Madre",
    "Codigo de firma de contrato",
]

# Expected output CSV columns (29 columns for SN system)
OUTPUT_COLUMNS = [
    "rbd",
    "year",
    "nivel",
    "curso",
    "local",
    "fechaMatricula",
    "estudiantePaterno",
    "estudianteMaterno",
    "estudianteNombre1",
    "estudianteNombre2",
    "estudianteEmail",
    "sexo",
    "estudianteRun",
    "fechaNacimiento",
    "direccion",
    "tutor1Nombre1",
    "tutor1Nombre2",
    "tutor1Paterno",
    "tutor1Materno",
    "tutor1Run",
    "tutor1Email",
    "tutor1Celular",
    "tutor2Nombre1",
    "tutor2Nombre2",
    "tutor2Paterno",
    "tutor2Materno",
    "tutor2Run",
    "tutor2Email",
    "tutor2Celular",
]

# Column renaming mapping
COLUMN_RENAME_MAP = {
    "curso_2024": "curso",
    "Nivel": "nivel",
    "Apellido Paterno": "estudiantePaterno",
    "Apellido Materno": "estudianteMaterno",
    "Rut": "estudianteRun",
    "Fecha de Nacimiento": "fechaNacimiento",
    "Fecha de Matrícula": "fechaMatricula",
    "Primer Nombre Alumno": "estudianteNombre1",
    "Segundo Nombre Alumno": "estudianteNombre2",
    "Sexo": "sexo",
    "Email Estudiante": "estudianteEmail",
    "full address": "direccion",
    "Primer Nombre Apoderado": "tutor1Nombre1",
    "Segundo Nombre Apoderado": "tutor1Nombre2",
    "Apellido Paterno Apo.": "tutor1Paterno",
    "Apellido Materno Apo.": "tutor1Materno",
    "Rut Apoderado": "tutor1Run",
    "Email Apoderado": "tutor1Email",
    "Celular Apoderado": "tutor1Celular",
    "Primer Nombre Apoderado SPL": "tutor2Nombre1",
    "Segundo Nombre Apoderado SPL": "tutor2Nombre2",
    "Apellido Paterno Apo. SPL": "tutor2Paterno",
    "Apellido Materno Apo. SPL": "tutor2Materno",
    "Rut Apoderado SPL": "tutor2Run",
    "Email Apoderado SPL": "tutor2Email",
    "Celular SPL": "tutor2Celular",
}
